### ISSUE TITLE
TypeError: req.body.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by mdanro** [amatelin/IoT.me#2]
mongod -version
db version v3.0.14

node -v
v7.2.1

The error is both traced and untraced and appears after you try to save or edit dataset fields

TypeError: req.body.hasOwnProperty is not a function
    at /home/dan/Documents/IoT.me-master/routes/datasets.js:143:22
    at Layer.handle [as handle_request] (/home/dan/Documents/IoT.me-master/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dan/Documents/IoT.me-master/node_modules/express/lib/router/route.js:131:13)
    at authenticate (/home/dan/Documents/IoT.me-master/utils.js:4:9)
    at Layer.handle [as handle_request] (/home/dan/Documents/IoT.me-master/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dan/Documents/IoT.me-master/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/dan/Documents/IoT.me-master/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/dan/Documents/IoT.me-master/node_modules/express/lib/router/layer.js:95:5)
    at /home/dan/Documents/IoT.me-master/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/dan/Documents/IoT.me-master/node_modules/express/lib/router/index.js:330:12)
    at next (/home/dan/Documents/IoT.me-master/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/home/dan/Documents/IoT.me-master/node_modules/express/lib/router/index.js:176:3)
    at router (/home/dan/Documents/IoT.me-master/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/home/dan/Documents/IoT.me-master/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/dan/Documents/IoT.me-master/node_modules/express/lib/router/index.js:312:13)
    at /home/dan/Documents/IoT.me-master/node_modules/express/lib/router/index.js:280:7

**Comment by yacob89** [comment]
I know this is an old issue but hopefully this helps. It works for me
https://github.com/expressjs/express/issues/3264#issuecomment-290480516

**Comment by sjh836** [comment]
The problem is that `express.urlencoded` default value(=false) uses querystring.parse().

Globally elegant If you want `req.body` to inherit an object, change extended to true.

Then use `qs.parse` to inherit the object. you can use `hasOwnProperty()`.

**Comment by Rafo99** [comment]
bodyParser.urlencoded({ extended: false }). Change false to true.
